server:

  port: 8999

 

eureka:

  instance:

    hostname: localhost  

 

spring:

  application:

    name: Gateway_API_Service

    

  cloud:

    gateway:

      routes:

 

        - id: SportsProduct-service

          uri: lb://SportsProduct-service

          predicates:

            - Path=/pps/**
          